### ISSUE TITLE
最近站点样式塌了，有待解决

### ISSUE THREAD

**Issue by hoochanlon** [zc-zh-001/ShadowSocks-Share#11]
![](http://p4.cdn.img9.top/ipfs/QmYpmNHDyuGQFFAe1nwxS6FD35ABbCpV9EEQLBA1wcKN92?4.png)

**Comment by zc-zh-001** [comment]
已修复，强制刷新

**Comment by loremwalker** [comment]
是云cdn那端有问题还是？
