### ISSUE TITLE
可否提供一个机制，让其他人可以提交账号到这个框架

### ISSUE THREAD

**Issue by ggzzzzzzz** [zc-zh-001/ShadowSocks-Share#4]
非常感谢作者的分享，这个工具很有用。分享账号的网页有很多不同的格式，网页格式本身也会发生变化，维护这些爬虫代码挺麻烦的。可否考虑提供一个API或机制，让其他人可以提交账号到这个框架，有这个框架来进行测试、分享。这样可以降低维护爬虫代码的负担。

**Comment by zc-zh-001** [comment]
这个想法挺好的，问题是与本项目的定位有所不同。
项目目标是**汇总免费账号，提供订阅服务，让大家方便订阅**。而不在于提供 ss 服务和 账号管理功能。
我的想法是，分享、维护账号的网站有很多，大家可以去分享，这里只负责收集信息，然后提供订阅服务。
看看项目后期的使用反馈吧。如果真的很有必要，后期可以添加相关功能的，谢谢。
