### ISSUE TITLE
想修改下导入订阅源的文字

### ISSUE THREAD

**Issue by hoochanlon** [zc-zh-001/ShadowSocks-Share#5]
想修改一下一导入订阅源的网址就显示的名称，“Shadowsocks Share”这样改成其他的名称像坚果面馆这样，不知道是那个文件
![rss](https://s1.ax2x.com/2018/04/25/8JGwr.png)

**Comment by zc-zh-001** [comment]
application.yml 文件中，增加（修改）

server:
  servlet:
    application-display-name: ShadowSocks-Share

**Comment by zc-zh-001** [comment]
二级目录里面的 没法修改，默认取了 url
