### ISSUE TITLE
免费ss账号网址

### ISSUE THREAD

**Issue by zyt760** [zc-zh-001/ShadowSocks-Share#5]
free.yitianjianss.com
gdmi.weebly.com/3118523398online.html
1hv.top
技术小白，不会改代码，望大佬添加。

**Comment by zc-zh-001** [comment]
前两个已添加，最后一个好像只有一个账号，先不添加了。现在的账号足够用了

**Comment by zc-zh-001** [comment]
gdmi.weebly.com/3118523398online.html  账号总是不可用啊

**Comment by zyt760** [comment]
我之前一直以为是IP被墙了，看来不是……

**Comment by zyt760** [comment]
https://github.com/Alvin9999/new-pac/wiki/ss免费账号
https://github.com/gfw-breaker/ssr-accounts

**Comment by zc-zh-001** [comment]
感性分享。现在账号总数70+，有效的超过20。咱们可以用质量好的账号替换一些质量不好的，总量不用太高，够用即可。

**Comment by hoochanlon** [comment]
已改名，重新部署了一下还是不行
![](https://s1.ax2x.com/2018/05/03/SMS6K.png)
