### ISSUE TITLE
订阅地址

### ISSUE THREAD

**Issue by FGorGor** [zc-zh-001/ShadowSocks-Share#6]
是这个吗？https://shadowsocks-share.herokuapp.com/subscribe?valid=1
订阅不了

**Comment by zc-zh-001** [comment]
什么客户端？为何不能订阅？

**Comment by FGorGor** [comment]
ssr 安卓4.08 就是输入上面的地址，订阅不了

2018年2月20日 下午6:09，"zc-zh-001" <notifications@github.com>写道：

**Comment by zc-zh-001** [comment]
@FGorGor 你再试试，不行的话下载最新客户端  https://github.com/shadowsocksrr/shadowsocksr-android/releases

**Comment by FGorGor** [comment]
好的谢谢

2018年2月21日 上午11:14，"zc-zh-001" <notifications@github.com>写道：

**Comment by FGorGor** [comment]
OK，现在我之前用的app也能订阅了，谢谢大神

2018年2月21日 上午11:14，"zc-zh-001" <notifications@github.com>写道：
