### ISSUE TITLE
ShadowRocket无法正常订阅

### ISSUE THREAD

**Issue by jzzzr501** [zc-zh-001/ShadowSocks-Share#7]
IOS平台的SS客户端，国区下架前最后一个版本2.1.13(527)

提示 不能获取订阅节点

Ps 用过其他项目的订阅可用。

**Comment by zc-zh-001** [comment]
这个有点麻烦，安装不了客户端我也没法测试了。
要不先提供个可用的订阅地址，我比较下有啥区别

**Comment by jzzzr501** [comment]
http://ss.pythonic.life/subscribe

**Comment by zc-zh-001** [comment]
@jzzzr501 现在试试

**Comment by jzzzr501** [comment]
可以了，感谢。也想知道有什么区别。

**Comment by zc-zh-001** [comment]
按规范，多链接组合用换行分隔或空格分隔，之前用了空格，该成换行，你这就可用了

**Comment by jzzzr501** [comment]
谢谢解惑。感谢。
